### ISSUE TITLE
What do you mean by "Pherkin isn't really fit for purpose yet"

### ISSUE THREAD

**Issue by vashishthask** [sheriff/test-bdd-cucumber-perl#52]
Does that mean it lacks some important features or what?

**Comment by sheriff** [comment]
When that was written, it felt like it was lacking many important features. However, over the last few years, features have been added as needed, and most everything you'd expect from it is now there. Let me know if you find anything missing.

**Comment by vashishthask** [comment]
It will be great if you could update the README then.
